### ISSUE TITLE
add_filter wpautop break some plugins/extensions

### ISSUE THREAD

**Issue by dantahoua** [waqastudios/inti-foundation#1]
Hello!
I tried your great theme. It seems that those two line:
remove_filter( 'the_content', 'wpautop' );
add_filter( 'the_content', 'wpautop' , 99);
break some of my plugin and other extension. The Formudible Pro plugin is one of those, I ended up with <br> tags added everywhere! 
When removing the filter, I evidently end with a lot of paragraph everywhere in the code generated by the shortcode...
Any idea? :)

**Comment by dantahoua** [comment]
I added this code I found on the web in the shortcodes.php file for now... I commented the two wpautop line and then:
`add_filter( 'the_content', 'tgm_io_shortcode_empty_paragraph_fix' );
function tgm_io_shortcode_empty_paragraph_fix( $content ) {
    $array = array(
        '<p>['    => '[',
        ']</p>'   => ']',
        ']<br />' => ']'
    );
    return strtr( $content, $array );
}`

**Comment by stuartstarrs** [comment]
Hey @dantahoua - both of those solutions receive some hate - both would be rejected in theme repositories. (Here are a couple of other options: http://betterwp.net/protect-shortcodes-from-wpautop-and-the-likes/)

My preference would be to implement the most generic solution, and make it easy to remove and change if needed. I think the one you have posted is consistently possibly less intrusive and probably better for most people.

**Comment by dantahoua** [comment]
Totaly agree! :)
