### ISSUE TITLE
Unexpected end of file inti-options.php

### ISSUE THREAD

**Issue by monicasolis** [waqastudios/inti-foundation#2]
Working on an Inti Foundation site, and when I activating this or a child theme, I have this error:

Parse error: syntax error, unexpected end of file in C:\wamp\www\dh\wp-content\themes\inti-foundation\framework\theme-options\inti-options.php on line 1836

Which version of PHP do I need?  I have 5.5 running; maybe that's the problem?

**Comment by stuartstarrs** [comment]
Every curly bracket is closed. The issue is likely the blank space, line 1836. Adding to JIRA.
