### ISSUE TITLE
Integrate "Live Reload"

### ISSUE THREAD

**Issue by pablopaul** [waqastudios/inti-foundation#4]
Any planes to bring "Live Reload" to the page by default?

**Comment by stuartstarrs** [comment]
In Gulp, as in _gulp-livereload_? It would be quite easy to add...
[gulp-livereload](https://www.npmjs.com/package/gulp-livereload)

I worry about adding tonnes of stuff that people might not use. That's kind of what the inti-kitchen-sink child theme is about, where everything is tweaked and overwritten and added to just to see what can be done. Maybe we could add _gulp-livereload_ to that and people could copy it over if they are using the parent theme or making their own child theme?

Very interested in all thoughts and opinions.

**Comment by pablopaul** [comment]
@stuartstarrs great idea to keep the foundation lean and add possible enhancements to the fully blown kitchen sink. We could add in the readme of the foundation that the kitchen sink will also educate on workflow improvements etc

**Comment by stuartstarrs** [comment]
@pablopaul finally got this added in [inti-kitchen-sink](https://github.com/waqastudios/inti-kitchen-sink)
